

@enum StatsName begin
    CACHED_ASSET_LOADING
    CACHED_IMAGE_LOADING
    CACHED_MESH_LOADING
    CACHED_SOUND_LOADING

    CHECK_ALL_SPRITES_READY_TO_RENDER

    FULL_LOGIC

    HANDLE_PROPAGATION_EVENT
    HANDLE_SINGLE_EVENT

    IDLE_TIME
    IDLE_TIME_5SEC

    INVOKE_BEGIN_CALLBACK
    INVOKE_EVENT_CALLBACK

    INPUT_TIME

    JIT_MOUSE_TEXTURE_LOADING

    LOGIC

    MEMORY_DECOMPRESSION

    MESH_LOADING_STATS
    
    ON_LOGIC_FRAME_END

    PROCESS_RAM_UNLOAD_QUEUE

    SCRIPT_LOADING

    TEXTURE_AFTER_RENDER
    TEXTURE_IMAGE_LOADING_STATS
    TEXTURE_PRELOAD_ADVISING
    TEXTURE_RENDERING
    TEXTURE_UPLOADS
    RENDER

    USER_INIT

    VIDEO_FRAME_DRIFT
end
